name = "ring"
main = "src/index.ts"
compatibility_date = "2022-11-01"
workers_dev = false

kv_namespaces = [
    { binding = "CONFIG", id = "46861e4463a1436a8fe164b9aafbbf21", preview_id = "1f50a360fcff4cda89ab850a78b2fbfa"},
]

[durable_objects]
bindings = [{name = "RING", class_name = "Node"}]

[vars]
ENVIRONMENT = "production"

[[unsafe.bindings]]
type = "analytics_engine"
name = "NODE_DATA"
dataset = "RING_NODE_DATA"

[[unsafe.bindings]]
type = "analytics_engine"
name = "CLUSTER_DATA"
dataset = "RING_CLUSTER_DATA"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Node"]
